/**
 * Las frases de la mascota (SCRUM-129).
 *
 * Un banco general y versatil: sirve a cualquier avatar, incluido uno
 * personalizado, y a cualquier persona. Por eso:
 *
 * - **No nombran al personaje** ni nada que solo sea suyo (un hilo, una luz, un
 *   cristal). Cada personaje conserva ademas sus frases propias, en
 *   `personajes.ts`, que se suman a las del momento "general".
 * - **No llevan genero** hacia quien las lee: ni "tranquilo" ni "cansada".
 *   Hay una prueba que lo vigila.
 * - **No hablan de sintomas, diagnosticos ni tratamientos**, y no aconsejan
 *   sobre salud: acompanan. Tampoco evaluan, ni piden nada con prisa, ni dejan
 *   culpa. Una frase de la racha no promete un numero de dias: la mascota no lo
 *   sabe, y una frase que no es cierta se nota.
 * - Son cortas: se leen en un globo.
 *
 * Estos textos llevan tildes y enes, al contrario que el resto del codigo: son
 * lo que alguien lee en pantalla. Una prueba comprueba que no falte ninguna.
 *
 * Se agrupan por momento. Cual toca lo decide `bancoDeFrases.ts`.
 */

/** Cuando se dice la frase. */
export type Momento = 'manana' | 'noche' | 'actividad' | 'racha' | 'diario' | 'general';

export const MOMENTOS: readonly Momento[] = [
  'manana',
  'noche',
  'actividad',
  'racha',
  'diario',
  'general',
];

export const FRASES_POR_MOMENTO: Readonly<Record<Momento, readonly string[]>> = {
  /** De las cinco a las doce del dia. */
  manana: [
    '¡Buenos días! Hoy empieza en blanco.',
    'Un día nuevo, con espacio para lo que quieras.',
    'Buenos días. Empezamos con calma.',
    'Buen día para dar un primer paso pequeño.',
    'Qué bueno verte por aquí esta mañana.',
    'La mañana es buen momento para elegir una cosa y empezar por ella.',
    'Hoy no hace falta hacerlo todo. Con un paso basta.',
    'Buenos días. Lo de ayer ya quedó atrás.',
    'Empieza por lo más fácil y deja que lo demás llegue.',
    'Un buen comienzo no necesita perfección.',
    'Hola, hola. ¿Con qué empezamos hoy?',
    'Que tu mañana vaya a tu ritmo.',
    'Hoy es una página limpia. Escribe lo que quieras.',
    'Buenos días. Qué gusto empezar contigo.',
    'Lo bueno de la mañana: todo está por hacerse.',
    'Un paso corto cuenta igual que uno largo.',
    'Hoy puedes ir despacio y aun así avanzar.',
    'Buen día. Aquí estoy para lo que necesites.',
    'Cada mañana es otra oportunidad de empezar a tu manera.',
    'No hay prisa. El día es largo y tienes tiempo.',
    'Arranquemos suave: primero lo más sencillo.',
    'Hoy elige una cosa y hazla bien. Con eso alcanza.',
    'Buenos días. Que lo pequeño también cuente hoy.',
    'Una mañana con calma ya es un buen comienzo.',
    'El día empieza cuando tú digas.',
    'Hola. Hoy toca ir paso a paso.',
    'Buenos días. Qué bien que volviste.',
    'Empieza por donde te resulte más fácil.',
    'Hoy no tienes que demostrarle nada a nadie.',
    'Que este día te trate bien.',
    'Un día más para ir a tu paso.',
    'Los buenos días también cuentan: ya sumaste uno.',
    'Hoy puedes cambiar de plan las veces que haga falta.',
    'Con lo que hagas hoy, ya es suficiente.',
    'Mira por la ventana, respira y empieza cuando quieras.',
    'Buen día. Lo que tenga que salir, saldrá.',
    'Una cosa a la vez: así se llega lejos.',
    'Amanece y se abre un día entero para ti.',
    'Buenos días. Hoy te acompaño en lo que venga.',
    'Que la mañana te alcance para lo que importa.',
  ],

  /** De las ocho de la noche a las cinco de la madrugada. */
  noche: [
    'Buenas noches. Hoy hiciste lo que pudiste, y está bien.',
    'El día se cierra. Lo que quedó pendiente puede esperar.',
    'Mañana habrá otra oportunidad. Hoy, a soltar.',
    'Buenas noches. Gracias por pasar por aquí.',
    'Ya es hora de bajar el ritmo.',
    'Cerrar el día también es parte del camino.',
    'Lo de hoy, hoy se queda. Mañana empieza de cero.',
    'Que tengas una noche en calma.',
    'No hace falta repasar el día. Con haber llegado, basta.',
    'Hoy sumaste, aunque no lo parezca.',
    'Buenas noches. Aquí estaré cuando vuelvas.',
    'La noche es para soltar lo que no se resolvió.',
    'Otro día que ya quedó contado.',
    'Apaga lo que puedas y deja lo demás para mañana.',
    'Buenas noches. Fue un buen día para intentar.',
    'Lo que hiciste hoy cuenta, sea mucho o poco.',
    'Ya hiciste bastante por hoy.',
    'Que la noche te sea suave.',
    'Mañana te espero con calma.',
    'Cada noche cierra un día y abre otro.',
    'Nada urgente a esta hora: todo puede esperar a mañana.',
    'Descansa la cabeza: mañana seguimos.',
    'El día no tiene que haber sido perfecto para haber valido.',
    'Buenas noches. Qué bueno que estuviste hoy.',
    'Un rato de calma antes de cerrar el día.',
    'A esta hora, lo mejor es ir más despacio.',
    'Mañana no te pido nada nuevo. Solo seguir.',
    'Hasta mañana. Aquí te guardo el lugar.',
    'Que lo bueno del día te acompañe esta noche.',
    'Lo que no salió hoy puede salir mañana.',
    'Cierra el día sin cuentas pendientes contigo.',
    'Buenas noches. Con lo de hoy fue suficiente.',
    'Es de noche: el mundo también va más lento.',
    'Una última pausa y se acabó el día.',
    'Hoy fue un día más en tu camino, y eso ya es mucho.',
    'Mañana habrá luz de nuevo.',
    'Quédate con una cosa buena del día y suelta el resto.',
    'Que descanses lo que te toca descansar.',
    'Buenas noches. Mañana, a tu paso.',
    'Gracias por dedicarte este rato hoy.',
  ],

  /** Justo despues de terminar una actividad. */
  actividad: [
    '¡Bien hecho! Una actividad más a tu cuenta.',
    'Eso es. Un paso más en tu camino.',
    'Lo lograste. Tómate un momento para notarlo.',
    'Una menos, y sin prisa.',
    'Gracias por dedicarte este rato.',
    'Cada actividad suma, también esta.',
    'Ya está. Lo importante es que lo hiciste.',
    'Buen trabajo. Respira y sigue cuando quieras.',
    'Eso cuenta. Y cuenta mucho.',
    'Un rato para ti, y ya está hecho.',
    'Qué bien. Hoy diste un paso real.',
    'Hecho. Lo demás puede esperar un poco.',
    'Terminar algo, aunque sea pequeño, merece un aplauso.',
    'Bien. Sin compararte con nadie, solo contigo.',
    'Lo hiciste a tu manera, y así vale.',
    'Un paso más y sin dramas.',
    '¡Eso! Ahora un respiro, si quieres.',
    'Sumaste algo más a tu camino.',
    'Se nota el esfuerzo. Gracias por hacerlo.',
    'Una cosa a la vez, y esta ya quedó.',
    'Qué buen ritmo llevas: el tuyo.',
    'Terminaste. Date un momento para reconocerlo.',
    'Cada vez que lo haces, se vuelve un poco más tuyo.',
    'Misión cumplida. ¿Te tomas un respiro?',
    'No importa el resultado: importa que apareciste.',
    'Ya está hecho. Ahora, lo que quieras.',
    'Lo que hiciste hoy se queda contigo.',
    'Pequeño paso, buen paso.',
    'Así se construye un hábito: de a poquito.',
    'Esto también es avanzar.',
    'Bien por ti. Sin presión, a tu ritmo.',
    'Una actividad menos y una buena razón para sonreír.',
    'Lo hiciste. Ni más ni menos.',
    'Qué bueno que lo intentaste.',
    'Cumplido. Te mereces una pausa corta.',
    'Un logro pequeño sigue siendo un logro.',
    'Lo importante es la constancia, no la perfección.',
    'Gracias por cuidar este rato para ti.',
    'Buen cierre. ¿Seguimos o paramos aquí? Tú decides.',
    'Eso estuvo muy bien. Todo a su tiempo.',
  ],

  /**
   * Volver dia tras dia. Ninguna promete un numero de dias, y ninguna castiga
   * un dia que falto: el camino sigue ahi.
   */
  racha: [
    'Otro día, y otra vez aquí. Eso se llama constancia.',
    'Volver cada día es lo que más cuenta.',
    'Tu constancia se nota, aunque tú no la veas.',
    'Día tras día, así se hace un camino.',
    'Qué bonito verte volver una y otra vez.',
    'Una costumbre se arma con días como este.',
    'Seguir viniendo ya es una forma de avanzar.',
    'Sin prisa y sin pausa: ese es tu ritmo.',
    'Cada día que vuelves, el camino se hace más tuyo.',
    'Lo tuyo no es la velocidad, es la constancia.',
    'Otro día sumado. Se va armando algo bueno.',
    'Aquí otra vez, y eso ya es mucho.',
    'Lo que se hace seguido pesa más de lo que parece.',
    'Hoy sigues. Mañana también, si quieres.',
    'Los días se juntan y, de pronto, hay camino.',
    'La constancia no hace ruido, pero se nota.',
    'Un paso hoy, otro mañana: así funciona.',
    'Seguir es lo que importa, no qué tan rápido.',
    'Vas sumando días a tu manera.',
    'Cada vez que vuelves me da gusto.',
    'Lo pequeño, repetido, se vuelve grande.',
    'No hace falta hacerlo perfecto, solo volver.',
    'Qué buena costumbre estás armando.',
    'Un día a la vez. Hoy ya cuenta.',
    'Ahí vas, a tu paso y sin presión.',
    'Tu camino se hace caminando, y ya llevas un buen trecho.',
    'Que otro día más se sume a los tuyos.',
    'Aquí estamos de nuevo. Qué bien.',
    'Los hábitos se construyen con días normales como hoy.',
    'Que se note: sigues aquí.',
    'Repetir también es avanzar.',
    'Si un día falta, no pasa nada: el camino sigue ahí.',
    'Aquí siempre se puede retomar, sin cuentas ni reproches.',
    'Lo que sumas se queda, pase lo que pase.',
    'Hoy cuenta, igual que cuentan todos los demás.',
    'Gracias por seguir viniendo.',
    'Poco a poco, y ya se nota el recorrido.',
    'Una racha no es una carrera: es un buen paseo.',
    'Ir y volver, ir y volver. Así se avanza.',
    'Contigo, los días se sienten más acompañados.',
  ],

  /** Al escribir en el diario. */
  diario: [
    'Escribir es una forma de ponerle orden a las ideas.',
    'Aquí cabe lo que quieras contar, grande o pequeño.',
    'Una línea basta. No hace falta más.',
    'Es tu espacio: escribe como quieras.',
    'No hay una forma correcta de escribir un diario.',
    'Cuenta lo que pasó hoy, a tu manera.',
    'Una palabra, una frase, un párrafo: todo vale.',
    'Escribir un rato es regalarte atención.',
    'Hoy puede ser una frase, un recuerdo o un dibujo.',
    'Lo que escribes hoy, mañana será un recuerdo.',
    'Apuntar lo bueno ayuda a no perderlo de vista.',
    'También puedes escribir lo que no sabes cómo decir.',
    'Sin faltas que corregir ni nota que sacar.',
    'Tu diario no te evalúa: solo te escucha.',
    'Empieza por lo primero que se te venga a la cabeza.',
    'Un recuerdo pequeño también merece su página.',
    'Contarlo por escrito a veces lo hace más claro.',
    'Me gustaría saber qué te pasó de bueno hoy.',
    'Escribe sin filtro: aquí no hay público.',
    'Cada anotación es una foto de cómo fue tu día.',
    'Puedes escribir largo o corto. Tú mandas.',
    'Un día cualquiera también merece una anotación.',
    'Dibuja, tacha, reescribe: es tu página.',
    'Guarda aquí lo que quieras recordar.',
    'Tus palabras, tu ritmo, tu espacio.',
    'Escribir no tiene que servir para nada. Basta con hacerlo.',
    '¿Algo bueno de hoy? Apúntalo antes de que se escape.',
    'A veces, escribir es la mejor manera de empezar a ordenar.',
    'Aquí no hay respuestas correctas.',
    'Dale una vuelta a tu día y deja lo mejor por escrito.',
    'Una frase sincera vale más que un párrafo bonito.',
    'Hoy puedes escribir sobre lo que te haya llamado la atención.',
    'Tu historia se escribe un día a la vez.',
    'Escribe para ti, no para que quede bonito.',
    'Que no te preocupe la ortografía: aquí se entiende todo.',
    'Anota lo que quieras recordar de hoy.',
    'Regálate un ratito de papel y lápiz, o de teclado.',
    'Lo que hoy parece poca cosa, mañana puede ser un buen recuerdo.',
    'Cada anotación es un paso para conocerte mejor.',
    'Un diario es un amigo que siempre escucha.',
  ],

  /** Cuando no hay un momento concreto: la tarde, y lo que no encaja en otro. */
  general: [
    'Aquí estoy. Sin prisa.',
    'Un paso pequeño también es un paso.',
    'Hoy puedes ir a tu ritmo.',
    'Qué bueno verte.',
    'No tienes que poder con todo hoy.',
    'Un respiro y seguimos.',
    'Lo estás haciendo mejor de lo que crees.',
    'Estoy contigo, venga lo que venga.',
    'Una cosa a la vez.',
    'Todo lo que sumas cuenta.',
    'No hay prisa. Aquí se avanza a tu paso.',
    'Si quieres, empezamos por lo más sencillo.',
    'Tómate el tiempo que necesites.',
    'Aquí no se juzga a nadie, y menos a ti.',
    'Con un poco cada día se llega lejos.',
    'Qué bien que pasaste por aquí.',
    'Hoy basta con aparecer.',
    'Cada día es una oportunidad nueva.',
    'Date permiso para ir despacio.',
    'Lo bueno no siempre es rápido.',
    'Hoy cuenta, aunque sea poquito.',
    'Un día a la vez es suficiente.',
    'Me gusta acompañarte.',
    'Lo que hagas hoy suma.',
    'Nadie lo hace perfecto. Tú tampoco tienes que.',
    'A veces lo mejor es empezar sin pensarlo tanto.',
    'Cuando quieras, aquí seguimos.',
    'Pequeño avance, gran diferencia.',
    'Un momento para ti también es parte del día.',
    'Aquí siempre hay espacio para ti.',
    'Confía en tu propio paso.',
    'Se puede empezar de nuevo las veces que haga falta.',
    'Sin culpas: lo que importa es lo que viene.',
    'Un poco de calma también es avanzar.',
    'Gracias por estar aquí.',
    'Cada intento cuenta, salga como salga.',
    'Hoy no tiene que ser un gran día. Con uno normal alcanza.',
    'Lo estás intentando, y eso es lo que cuenta.',
    'Lo que importa es seguir, no llegar primero.',
    'Hay días de correr y días de caminar. Hoy elige tú.',
  ],
};

/** Todas las frases del banco, de todos los momentos. */
export const TODAS_LAS_FRASES: readonly string[] = MOMENTOS.flatMap(
  (momento) => FRASES_POR_MOMENTO[momento],
);
